/**
 * Deploy Dog House suite → deployments.json + src/lib/web3/deployments.generated.ts
 *
 * Usage:
 *   npx hardhat run scripts/deploySuite.ts --network monadTestnet
 *   npx hardhat run scripts/deploySuite.ts --network monad
 */
import { ethers, network } from "hardhat";
import fs from "fs";
import path from "path";

type SuiteAddresses = {
  tokenLock: string;
  vestingNFT: string;
  streamFarm: string;
  otcMarket: string;
};

function writeGeneratedTs(chainId: number, addrs: SuiteAddresses) {
  const out = path.resolve(__dirname, "../../src/lib/web3/deployments.generated.ts");
  const body = `/** Auto-generated by contracts/scripts/deploySuite.ts — do not edit manually */
export const TESTNET_DEPLOYMENTS = {
  chainId: ${chainId},
  tokenLock: "${addrs.tokenLock}" as \`0x\${string}\`,
  vestingNFT: "${addrs.vestingNFT}" as \`0x\${string}\`,
  streamFarm: "${addrs.streamFarm}" as \`0x\${string}\`,
  otcMarket: "${addrs.otcMarket}" as \`0x\${string}\`,
};
`;
  fs.writeFileSync(out, body);
  console.log("Wrote", out);
}

async function main() {
  const [deployer] = await ethers.getSigners();
  const net = await ethers.provider.getNetwork();
  const chainId = Number(net.chainId);

  console.log("Deployer:", deployer.address);
  console.log("Network: ", network.name, `(chainId ${chainId})`);
  console.log(
    "Balance: ",
    ethers.formatEther(await ethers.provider.getBalance(deployer.address)),
    "MON\n",
  );

  console.log("[1/4] TokenLockNFT...");
  const TokenLockNFT = await ethers.getContractFactory("TokenLockNFT");
  const lock = await TokenLockNFT.deploy();
  await lock.waitForDeployment();
  const tokenLock = await lock.getAddress();
  console.log("      ", tokenLock);

  console.log("[2/4] VestingNFT...");
  const VestingNFT = await ethers.getContractFactory("VestingNFT");
  const vesting = await VestingNFT.deploy();
  await vesting.waitForDeployment();
  const vestingNFT = await vesting.getAddress();
  console.log("      ", vestingNFT);

  console.log("[3/4] StreamFarm...");
  const StreamFarm = await ethers.getContractFactory("StreamFarm");
  const farm = await StreamFarm.deploy();
  await farm.waitForDeployment();
  const streamFarm = await farm.getAddress();
  console.log("      ", streamFarm);

  console.log("[4/4] OTCMarket...");
  const OTCMarket = await ethers.getContractFactory("OTCMarket");
  const otc = await OTCMarket.deploy();
  await otc.waitForDeployment();
  const otcMarket = await otc.getAddress();
  console.log("      ", otcMarket);

  const addrs: SuiteAddresses = { tokenLock, vestingNFT, streamFarm, otcMarket };

  const deploymentsPath = path.resolve(__dirname, "..", "deployments.json");
  let deployments: Record<string, unknown> = {};
  try {
    deployments = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));
  } catch {
    /* new file */
  }
  deployments[String(chainId)] = {
    TokenLockNFT: tokenLock,
    VestingNFT: vestingNFT,
    StreamFarm: streamFarm,
    OTCMarket: otcMarket,
    deployedAt: new Date().toISOString(),
    network: network.name,
  };
  fs.writeFileSync(deploymentsPath, JSON.stringify(deployments, null, 2));
  console.log("\nSaved", deploymentsPath);

  writeGeneratedTs(chainId, addrs);

  console.log("\n--- Copy to .env.local (mainnet) if chainId 143 ---");
  console.log(`VITE_TOKEN_LOCK_MAINNET=${tokenLock}`);
  console.log(`VITE_VESTING_NFT_MAINNET=${vestingNFT}`);
  console.log(`VITE_STREAM_FARM_MAINNET=${streamFarm}`);
  console.log(`VITE_OTC_MARKET_MAINNET=${otcMarket}`);
  console.log("\nDone.");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
