/** Auto-generated by contracts/scripts/deploySuite.ts — do not edit manually */
export const MAINNET_DEPLOYMENTS = {
  chainId: 143,
  tokenLock: "0x8Ed0987b36655AF304c65DFea3c5eb55478f3B95" as `0x${string}`,
  vestingNFT: "0x00081D91D90c2D980793543f9ED67124229dAeE2" as `0x${string}`,
  streamFarm: "0xF3499196F8bd6E6d499a5A68dbeD30C78137e940" as `0x${string}`,
  otcMarket: "0x9c98C243978240C43A151fd1ebBD5DCb40BE5624" as `0x${string}`,
};
