/** Auto-generated by contracts/scripts/deploySuite.ts — do not edit manually */
export const TESTNET_DEPLOYMENTS = {
  chainId: 10143,
  tokenLock: "0x1B326887e87D6671D5c34FB79F66d72B446D0aF0" as `0x${string}`,
  vestingNFT: "0xfAb8d05E96E8295999AB00Bb20E7973CfdaC2D48" as `0x${string}`,
  streamFarm: "0x736F281DB537B1595f74320995903666e804B80E" as `0x${string}`,
  otcMarket: "0x1adA395947Cbc576D151fF4b8E0A337d8d1F78aA" as `0x${string}`,
};
