/** Auto-generated by contracts/scripts/deploySuite.ts — do not edit manually */
export const MAINNET_DEPLOYMENTS = {
  chainId: 143,
  tokenLock: "0x827Ea3e3a738B48508566a2C84E12F0e39F41E98" as `0x${string}`,
  vestingNFT: "0xb56602b10794D6b63aFB6c74a770C628364826b6" as `0x${string}`,
  streamFarm: "0x66e0Ff9323f2BCDE3b73656d0c2E1Aa03Bf894fe" as `0x${string}`,
  otcMarket: "0xEAA8aa3dc694B1fAF238bf30E7B3aeD36c649BD6" as `0x${string}`,
};
