/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VestingRouteImport } from './routes/vesting'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as LockRouteImport } from './routes/lock'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClmmRouteImport } from './routes/clmm'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VestingRoute = VestingRouteImport.update({
  id: '/vesting',
  path: '/vesting',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClmmRoute = ClmmRouteImport.update({
  id: '/clmm',
  path: '/clmm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clmm': typeof ClmmRoute
  '/dashboard': typeof DashboardRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/transfer': typeof TransferRoute
  '/vesting': typeof VestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clmm': typeof ClmmRoute
  '/dashboard': typeof DashboardRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/transfer': typeof TransferRoute
  '/vesting': typeof VestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clmm': typeof ClmmRoute
  '/dashboard': typeof DashboardRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/transfer': typeof TransferRoute
  '/vesting': typeof VestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clmm'
    | '/dashboard'
    | '/farm'
    | '/lock'
    | '/transfer'
    | '/vesting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clmm'
    | '/dashboard'
    | '/farm'
    | '/lock'
    | '/transfer'
    | '/vesting'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clmm'
    | '/dashboard'
    | '/farm'
    | '/lock'
    | '/transfer'
    | '/vesting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClmmRoute: typeof ClmmRoute
  DashboardRoute: typeof DashboardRoute
  FarmRoute: typeof FarmRoute
  LockRoute: typeof LockRoute
  TransferRoute: typeof TransferRoute
  VestingRoute: typeof VestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vesting': {
      id: '/vesting'
      path: '/vesting'
      fullPath: '/vesting'
      preLoaderRoute: typeof VestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clmm': {
      id: '/clmm'
      path: '/clmm'
      fullPath: '/clmm'
      preLoaderRoute: typeof ClmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClmmRoute: ClmmRoute,
  DashboardRoute: DashboardRoute,
  FarmRoute: FarmRoute,
  LockRoute: LockRoute,
  TransferRoute: TransferRoute,
  VestingRoute: VestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
