/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VestingRouteImport } from './routes/vesting'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as OtcRouteImport } from './routes/otc'
import { Route as LockRouteImport } from './routes/lock'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClmmRouteImport } from './routes/clmm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClmmPoolPoolAddressRouteImport } from './routes/clmm.pool.$poolAddress'
import { Route as ClmmPoolPoolAddressAddRouteImport } from './routes/clmm.pool.$poolAddress.add'

const VestingRoute = VestingRouteImport.update({
  id: '/vesting',
  path: '/vesting',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const OtcRoute = OtcRouteImport.update({
  id: '/otc',
  path: '/otc',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClmmRoute = ClmmRouteImport.update({
  id: '/clmm',
  path: '/clmm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClmmPoolPoolAddressRoute = ClmmPoolPoolAddressRouteImport.update({
  id: '/pool/$poolAddress',
  path: '/pool/$poolAddress',
  getParentRoute: () => ClmmRoute,
} as any)
const ClmmPoolPoolAddressAddRoute = ClmmPoolPoolAddressAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ClmmPoolPoolAddressRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clmm': typeof ClmmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/otc': typeof OtcRoute
  '/transfer': typeof TransferRoute
  '/vesting': typeof VestingRoute
  '/clmm/pool/$poolAddress': typeof ClmmPoolPoolAddressRouteWithChildren
  '/clmm/pool/$poolAddress/add': typeof ClmmPoolPoolAddressAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clmm': typeof ClmmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/otc': typeof OtcRoute
  '/transfer': typeof TransferRoute
  '/vesting': typeof VestingRoute
  '/clmm/pool/$poolAddress': typeof ClmmPoolPoolAddressRouteWithChildren
  '/clmm/pool/$poolAddress/add': typeof ClmmPoolPoolAddressAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clmm': typeof ClmmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/otc': typeof OtcRoute
  '/transfer': typeof TransferRoute
  '/vesting': typeof VestingRoute
  '/clmm/pool/$poolAddress': typeof ClmmPoolPoolAddressRouteWithChildren
  '/clmm/pool/$poolAddress/add': typeof ClmmPoolPoolAddressAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clmm'
    | '/dashboard'
    | '/farm'
    | '/lock'
    | '/otc'
    | '/transfer'
    | '/vesting'
    | '/clmm/pool/$poolAddress'
    | '/clmm/pool/$poolAddress/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clmm'
    | '/dashboard'
    | '/farm'
    | '/lock'
    | '/otc'
    | '/transfer'
    | '/vesting'
    | '/clmm/pool/$poolAddress'
    | '/clmm/pool/$poolAddress/add'
  id:
    | '__root__'
    | '/'
    | '/clmm'
    | '/dashboard'
    | '/farm'
    | '/lock'
    | '/otc'
    | '/transfer'
    | '/vesting'
    | '/clmm/pool/$poolAddress'
    | '/clmm/pool/$poolAddress/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClmmRoute: typeof ClmmRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FarmRoute: typeof FarmRoute
  LockRoute: typeof LockRoute
  OtcRoute: typeof OtcRoute
  TransferRoute: typeof TransferRoute
  VestingRoute: typeof VestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vesting': {
      id: '/vesting'
      path: '/vesting'
      fullPath: '/vesting'
      preLoaderRoute: typeof VestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otc': {
      id: '/otc'
      path: '/otc'
      fullPath: '/otc'
      preLoaderRoute: typeof OtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clmm': {
      id: '/clmm'
      path: '/clmm'
      fullPath: '/clmm'
      preLoaderRoute: typeof ClmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clmm/pool/$poolAddress': {
      id: '/clmm/pool/$poolAddress'
      path: '/pool/$poolAddress'
      fullPath: '/clmm/pool/$poolAddress'
      preLoaderRoute: typeof ClmmPoolPoolAddressRouteImport
      parentRoute: typeof ClmmRoute
    }
    '/clmm/pool/$poolAddress/add': {
      id: '/clmm/pool/$poolAddress/add'
      path: '/add'
      fullPath: '/clmm/pool/$poolAddress/add'
      preLoaderRoute: typeof ClmmPoolPoolAddressAddRouteImport
      parentRoute: typeof ClmmPoolPoolAddressRoute
    }
  }
}

interface ClmmPoolPoolAddressRouteChildren {
  ClmmPoolPoolAddressAddRoute: typeof ClmmPoolPoolAddressAddRoute
}

const ClmmPoolPoolAddressRouteChildren: ClmmPoolPoolAddressRouteChildren = {
  ClmmPoolPoolAddressAddRoute: ClmmPoolPoolAddressAddRoute,
}

const ClmmPoolPoolAddressRouteWithChildren =
  ClmmPoolPoolAddressRoute._addFileChildren(ClmmPoolPoolAddressRouteChildren)

interface ClmmRouteChildren {
  ClmmPoolPoolAddressRoute: typeof ClmmPoolPoolAddressRouteWithChildren
}

const ClmmRouteChildren: ClmmRouteChildren = {
  ClmmPoolPoolAddressRoute: ClmmPoolPoolAddressRouteWithChildren,
}

const ClmmRouteWithChildren = ClmmRoute._addFileChildren(ClmmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClmmRoute: ClmmRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FarmRoute: FarmRoute,
  LockRoute: LockRoute,
  OtcRoute: OtcRoute,
  TransferRoute: TransferRoute,
  VestingRoute: VestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
